# Generated by Django 2.1.5 on 2019-04-10 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_make',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.VehicleModel'),
        ),
    ]
