# Generated by Django 2.1.5 on 2019-04-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190409_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='identifier',
        ),
    ]
