# Generated by Django 2.1.5 on 2019-04-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_sale_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Country'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='model_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Make'),
        ),
    ]
