# Generated by Django 2.1.5 on 2019-04-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190411_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='total_sales',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='total_sales',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_sales',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
